spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: digital-fine-management-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

allowed:
  origins:
    web: ${ALLOWED_ORIGINS_WEB}
    expo-officer: ${ALLOWED_ORIGINS_EXPO_OFFICER}
    expo-rider: ${ALLOWED_ORIGINS_EXPO_RIDER}

stripe:
  secret_key: ${STRIPE_SECRET_KEY}

